allowLineBreaksInTitles: false
color: blue
description: null
fieldLayouts:
  f2ad098f-47ec-4090-a10d-55c4921655d1:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-10T12:00:00+00:00'
            elementCondition: null
            heading: 'Section Header'
            type: craft\fieldlayoutelements\Heading
            uid: 175a9012-812c-4859-8f1e-f69eb20bb73c
            userCondition: null
          -
            dateAdded: '2026-09-10T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d5189384-3a6a-441f-9f4b-cb171f279337 # Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b58ee6d7-4b1e-4619-976e-f142be8b4bbf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-10T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7f0dd947-99d8-4456-93f3-4ce4f6162a3f # Rich Text - Simple
            handle: text
            instructions: null
            label: Text
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3017a3a-1326-445e-9eff-975338b142dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-10T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0b199c11-0b79-4e4b-b931-f9c85e23a667 # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c80131b4-ced6-4e54-a8d5-d1292a2b5aca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-10T12:00:00+00:00'
            elementCondition: null
            heading: 'Section Content'
            type: craft\fieldlayoutelements\Heading
            uid: 10ffd041-13b8-48fd-b47a-3ba909a57112
            userCondition: null
          -
            dateAdded: '2026-09-10T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            handle: null
            instructions: "A cutout with a transparent background. It stands on the banner's bottom edge and rises above its top."
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16af4f30-913e-49eb-893a-bafd87ee1c35
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 48c9ca69-0d67-40ad-a05c-96128f10c1dd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-10T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 502c0610-e74d-4359-8524-5652307ada64 # Padding
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57ea84c2-03e2-4546-9c5e-cfa6fe0ea17e
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 17131217-6deb-40c0-b46a-40975be0a975
        userCondition: null
    thumbFieldKey: null
handle: bannerCta
hasTitleField: false
icon: rectangle-wide
name: 'Banner - CTA'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
