allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  3a32145f-3fa4-4298-b457-ebb9d2981ef4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-08-28T12:01:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bf62465e-1e00-47ff-b541-5b7d03441b0f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ab214509-2da1-4b0b-b7a3-33dac1c86ce9 # Hero
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b759f0d1-d7a0-4587-b03f-bcffa5b1001a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T13:17:19+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 41118d3a-a4e2-4b8e-8d11-b0a93f26deeb # Lightswitch - On
            handle: tableOfContents
            instructions: null
            label: 'Table of Contents'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8463e023-421d-4cc6-af79-93fafc7b693a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T13:17:19+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7da91603-5ded-43ca-b8c9-692b445e049e # Rich Text - Longform
            handle: null
            instructions: null
            label: Longform
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4794ad22-7076-41b9-b95e-b37bd5b2f378
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 46d0692f-956d-40ae-b49b-5797bc13db20
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 453f9294-407d-405a-b73b-d5b63aec2eaa # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ce8fd10-4097-4361-815b-c88cdd497084
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 48f9e639-4545-4e9f-84af-eefc03e847eb
        userCondition: null
    thumbFieldKey: null
handle: entryText
hasTitleField: true
icon: file
name: 'Entry - Text'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
