allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  971fdba9-055c-48d8-aa82-c3452a7aff1b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-08-28T12:01:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9a27fd80-66d8-4ccf-8423-faaf3826b407
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ab214509-2da1-4b0b-b7a3-33dac1c86ce9 # Hero
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e418f3c-9aed-42bf-a829-6c65fdc79be0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 814aa3b0-3be9-40de-bc3f-cd416a87284a
            userCondition: null
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Case Study Entries will automatically pull through here'
            type: craft\fieldlayoutelements\Tip
            uid: 42a7d034-a021-4a83-871a-dfaa4de5a526
            userCondition: null
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 74fe7858-364e-48f2-8810-7ba9a1c1515a
            userCondition: null
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6b2462c2-66b9-45fe-9504-0bce4d4cd1df # Blocks
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0bc5702-35f2-4078-be99-1f213a1ef8b4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 259f5534-5e25-459a-9287-d11ce5ecf8eb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 453f9294-407d-405a-b73b-d5b63aec2eaa # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcd5fcb4-7fc7-41c1-8ea7-9dc12968183e
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: cd9a8d6a-245d-4eac-9288-2f9984a28efd
        userCondition: null
    thumbFieldKey: null
handle: entryCaseStudyListing
hasTitleField: true
icon: file
name: 'Entry - Case Study Listing'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
