allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  8b55a42c-7fb8-4ad8-9626-5b8cd6f2ea4c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-18T16:32:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ac34f9f6-f701-4ecf-91cf-56a580b37f89
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T13:59:53+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            handle: avatar
            instructions: null
            label: Avatar
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b284fd95-06ae-4661-9c0f-ab06d567b174
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T13:59:53+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: testimonialName
            instructions: null
            label: 'Testimonial Name'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f672357c-f582-4d59-a814-c08fab2124dd
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-28T13:59:53+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: testimonialJobRole
            instructions: null
            label: 'Testimonial Job Role'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cba436ba-ac72-41fb-bcc5-8662b47d5ad7
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-28T13:59:53+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            handle: logo
            instructions: null
            label: Logo
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62ad8270-ef4f-4fa6-b845-a3498a0e8797
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T13:59:53+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7f0dd947-99d8-4456-93f3-4ce4f6162a3f # Rich Text - Simple
            handle: text
            instructions: null
            label: Text
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5678e25-2252-4309-982a-6a1c556113fa
            userCondition: null
            warning: null
            width: 100
        name: 'Element Content'
        uid: 61c6a497-5cd7-43bb-877c-0c682cac4712
        userCondition: null
    thumbFieldKey: null
handle: entryTestimonial
hasTitleField: true
icon: file
name: 'Entry - Testimonial'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
