allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  efe509f4-ea8a-45f2-8600-7987d3c2168c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-08-28T12:01:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 74115512-51d4-44f0-b801-7c15631d012b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ab214509-2da1-4b0b-b7a3-33dac1c86ce9 # Hero
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17ed0417-1b90-4ef9-8f1f-8c5c0edb8bf6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: bb82166d-ad08-4d55-8062-aaf6737370ea
            userCondition: null
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Team Entries will automatically pull through here'
            type: craft\fieldlayoutelements\Tip
            uid: d8de41b5-76a5-4da4-a13c-918814b3855d
            userCondition: null
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: ea0ca312-0032-4d2d-8b21-d2a76335048d
            userCondition: null
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6b2462c2-66b9-45fe-9504-0bce4d4cd1df # Blocks
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c80c4e0-d39c-42b5-98a9-5f7895b488a3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e300461a-a1b6-4ee3-9aa9-6170f153e55c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 453f9294-407d-405a-b73b-d5b63aec2eaa # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53751be6-3155-495d-96eb-e8170734bf1a
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: a3b52e42-d0e1-4dce-b30c-5ff32a407b90
        userCondition: null
    thumbFieldKey: null
handle: entryTeamListing
hasTitleField: true
icon: file
name: 'Entry - Team Listing'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
