allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  1d3eddb3-1653-40d3-a89f-cbcc5824a691:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-18T16:32:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ecda5dd9-de6d-414a-aa3d-e672150067ab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-11T10:54:18+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1ef234a4-dca8-44db-bb95-619a3f11c7a2 # Categories - Career
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b30c163b-3b96-4d9c-833e-043c42cc62dc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-11T10:54:18+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f61a49ec-ae57-4242-8a0b-482661a55c30 # Dropdown - Employment Type
            handle: employmentType
            instructions: null
            label: 'Employment Type'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8045474-9e58-4385-a2a9-dd727e04faa5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-12T13:04:36+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: salary
            instructions: null
            label: Salary
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a3205d0-7ef5-4747-9378-5f979bf4a11d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-09-12T13:04:36+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: salaryFootnote
            instructions: null
            label: 'Salary Footnote'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c095f922-15d7-41cd-af49-3e537bde7a1d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-09-12T13:04:36+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: reportsTo
            instructions: null
            label: 'Reports To'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61cd9692-9c54-4e9a-8164-772116585b27
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-12T13:04:36+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: workingPattern
            instructions: null
            label: 'Working Pattern'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94271a43-d395-4a18-b747-3650b4666fee
            userCondition: null
            warning: null
            width: 100
        name: 'Overview Content'
        uid: 33309d6c-d4f5-4800-b814-56d28f69c086
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-28T13:42:12+00:00'
            elementCondition: null
            heading: Hero
            type: craft\fieldlayoutelements\Heading
            uid: 837f4bb9-7a65-41a7-8678-d886e72747ba
            userCondition: null
          -
            dateAdded: '2026-09-12T13:02:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d5189384-3a6a-441f-9f4b-cb171f279337 # Heading
            handle: heroHeading
            instructions: null
            label: 'Hero Heading'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6dd0c87-92b1-4aa5-b7b2-f69e79052588
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-12T13:02:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7f0dd947-99d8-4456-93f3-4ce4f6162a3f # Rich Text - Simple
            handle: heroText
            instructions: null
            label: 'Hero Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0756b59f-22eb-4209-a139-c97e583508f6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-12T13:02:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            handle: heroImage
            instructions: null
            label: 'Hero Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee95e639-6231-4ddb-bc6e-5ab99fd7eb6e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T13:42:12+00:00'
            elementCondition: null
            heading: Content
            type: craft\fieldlayoutelements\Heading
            uid: 48ae8fa7-e280-4932-aa54-6c0aaf0862bb
            userCondition: null
          -
            dateAdded: '2026-04-07T10:41:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6b2462c2-66b9-45fe-9504-0bce4d4cd1df # Blocks
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22c8e5a5-f515-43bd-9b40-7b92e188e2c6
            userCondition: null
            warning: null
            width: 100
        name: 'Page Content'
        uid: 560f5e2d-72a2-4468-b39e-32616eadd5bc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-28T11:22:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 453f9294-407d-405a-b73b-d5b63aec2eaa # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02fe65fc-dba7-454a-80e6-e05e48f8effb
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: b120fce9-4026-4aad-878c-160dc5f9e57e
        userCondition: null
    thumbFieldKey: null
handle: entryCareer
hasTitleField: true
icon: file
name: 'Entry - Career'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
