allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  1d3eddb3-1653-40d3-a89f-cbcc5824a691:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-18T16:32:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ecda5dd9-de6d-414a-aa3d-e672150067ab
            userCondition: null
            warning: null
            width: 100
        name: 'Overview Content'
        uid: 33309d6c-d4f5-4800-b814-56d28f69c086
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-28T13:42:12+00:00'
            elementCondition: null
            heading: Hero
            type: craft\fieldlayoutelements\Heading
            uid: 837f4bb9-7a65-41a7-8678-d886e72747ba
            userCondition: null
          -
            dateAdded: '2026-08-28T11:29:55+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ab214509-2da1-4b0b-b7a3-33dac1c86ce9 # Hero
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 734c2216-2dae-4bf7-bf75-33e44b2fc1b2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T13:42:12+00:00'
            elementCondition: null
            heading: Content
            type: craft\fieldlayoutelements\Heading
            uid: 48ae8fa7-e280-4932-aa54-6c0aaf0862bb
            userCondition: null
          -
            dateAdded: '2026-04-07T10:41:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6b2462c2-66b9-45fe-9504-0bce4d4cd1df # Blocks
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22c8e5a5-f515-43bd-9b40-7b92e188e2c6
            userCondition: null
            warning: null
            width: 100
        name: 'Page Content'
        uid: 560f5e2d-72a2-4468-b39e-32616eadd5bc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-28T11:22:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 453f9294-407d-405a-b73b-d5b63aec2eaa # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02fe65fc-dba7-454a-80e6-e05e48f8effb
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: b120fce9-4026-4aad-878c-160dc5f9e57e
        userCondition: null
    thumbFieldKey: null
handle: entryCareer
hasTitleField: true
icon: file
name: 'Entry - Career'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
