allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  ea7e7631-e1f3-4334-936c-f22e088e00cf:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-18T16:32:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dbd67718-9bb5-4372-bdaa-0fb43d271322
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T13:55:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aec5ba1c-6ef1-4412-a1cd-b0775ac28c61
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T13:55:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: jobRole
            instructions: null
            label: 'Job Role'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62979edc-591b-4fdf-bde7-210140f591dc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T13:55:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 13285537-5457-4f1f-ad8c-66fd187f8f09 # Rich Text - Full
            handle: text
            instructions: null
            label: Text
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06a6b4cb-8bac-43e8-be8a-25e0af0d227f
            userCondition: null
            warning: null
            width: 100
        name: 'Element Content'
        uid: 7f6acbd8-1755-4cd7-ba8d-7bf0f4516972
        userCondition: null
    thumbFieldKey: null
handle: entryTeam
hasTitleField: true
icon: file
name: 'Entry - Team'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
