allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  69e0f3f8-d55a-44bb-8f64-fc0e11b7daab:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-08-28T12:01:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 12a925a8-6748-4607-8ecd-3fd5fea4c9d8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ab214509-2da1-4b0b-b7a3-33dac1c86ce9 # Hero
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0990afe5-d51e-4c5b-b433-bef5d5361d50
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 119cd0e1-4007-46c4-959f-a3a15db9bf54
            userCondition: null
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'FAQ Entries will automatically pull through here'
            type: craft\fieldlayoutelements\Tip
            uid: ecdc89fe-b77e-4bbf-87b0-7732849a68e3
            userCondition: null
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: d5f35aa0-5f20-4271-8d6b-26c261dd4c6c
            userCondition: null
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6b2462c2-66b9-45fe-9504-0bce4d4cd1df # Blocks
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea8e7b78-bc9f-4b58-a77f-483028f8243a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f99e3736-7ae1-4d1b-973a-14d3ff571f0a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-28T12:04:14+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 453f9294-407d-405a-b73b-d5b63aec2eaa # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3932ba01-e93e-4b29-a0f6-f7ef7415b97e
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: a4670592-bd30-475e-991d-0c093f1e4f89
        userCondition: null
    thumbFieldKey: null
handle: entryFaqListing
hasTitleField: true
icon: file
name: 'Entry - FAQ Listing'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
