allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  a21c92b7-a638-4278-8cb7-5c786fc3c3b9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-18T16:32:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2197cb3a-aae1-439c-abd2-f5a40ea93498
            userCondition: null
            warning: null
            width: 100
        name: 'Overview Content'
        uid: 2c15df9d-c8e3-45e6-8eda-7ff23d9d47f3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-28T13:42:12+00:00'
            elementCondition: null
            heading: Hero
            type: craft\fieldlayoutelements\Heading
            uid: f6d87d5d-6960-4ab0-962a-c1a9cd4314f6
            userCondition: null
          -
            dateAdded: '2026-08-28T11:29:55+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ab214509-2da1-4b0b-b7a3-33dac1c86ce9 # Hero
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ecdce01a-3bab-43fc-a073-a76510ad47fe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T13:42:12+00:00'
            elementCondition: null
            heading: Content
            type: craft\fieldlayoutelements\Heading
            uid: 04c856f6-5dc2-4503-a6dc-e5c5579698fd
            userCondition: null
          -
            dateAdded: '2026-04-07T10:41:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6b2462c2-66b9-45fe-9504-0bce4d4cd1df # Blocks
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2da8faa2-9608-4a2f-bd48-09abd17969d8
            userCondition: null
            warning: null
            width: 100
        name: 'Page Content'
        uid: a4f82f35-83e3-48c5-99eb-39383bf0df00
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-28T11:22:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 453f9294-407d-405a-b73b-d5b63aec2eaa # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 469ee2ba-74f2-4d7d-8cc5-85eb5b9efe09
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 8c95c220-3fd4-4304-b302-288911be4914
        userCondition: null
    thumbFieldKey: null
handle: entryService
hasTitleField: true
icon: file
name: 'Entry - Service'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
