allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  2a334610-a7dd-40c3-8157-5e6b8679afad:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-18T16:32:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8f0c8579-9ce5-4d21-9171-aaa789ec4491
            userCondition: null
            warning: null
            width: 100
        name: 'Overview Content'
        uid: f1e7849b-41e3-4c43-91f6-e6c51a82644e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-28T13:42:12+00:00'
            elementCondition: null
            heading: Hero
            type: craft\fieldlayoutelements\Heading
            uid: d3ff6186-bdf1-48b5-a704-8fae1c3d9d74
            userCondition: null
          -
            dateAdded: '2026-08-28T11:29:55+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ab214509-2da1-4b0b-b7a3-33dac1c86ce9 # Hero
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c90776ec-e5ff-40d2-b2a3-b617627fbaa5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T13:42:12+00:00'
            elementCondition: null
            heading: Content
            type: craft\fieldlayoutelements\Heading
            uid: 6638044d-7451-4d05-a791-3e84640e306c
            userCondition: null
          -
            dateAdded: '2026-04-07T10:41:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6b2462c2-66b9-45fe-9504-0bce4d4cd1df # Blocks
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bedfc88-b103-4cde-8d70-ef98eec075d9
            userCondition: null
            warning: null
            width: 100
        name: 'Page Content'
        uid: 82c72f71-aada-4840-affc-884f1053c235
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-28T11:22:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 453f9294-407d-405a-b73b-d5b63aec2eaa # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48451f05-4d73-4fdb-a71f-949a211fe22a
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: fa9cc52c-9421-4da1-8907-c6e8f0a6e8bd
        userCondition: null
    thumbFieldKey: null
handle: entryCaseStudy
hasTitleField: true
icon: file
name: 'Entry - Case Study'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
