allowLineBreaksInTitles: false
color: blue
description: null
fieldLayouts:
  7e8151cd-d439-48a6-945d-65ebb718c73f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-09T12:00:00+00:00'
            elementCondition: null
            heading: 'Section Header'
            type: craft\fieldlayoutelements\Heading
            uid: 47f0ad51-8448-4a3d-84b2-cab9c20dc454
            userCondition: null
          -
            dateAdded: '2026-09-09T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bb417d14-872a-4288-9f03-8a735011cb7e # Eyebrow
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 180bb624-7e7b-40da-a970-3dfca5794e78
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-09T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d5189384-3a6a-441f-9f4b-cb171f279337 # Heading
            handle: null
            instructions: 'Make words italic to highlight them.'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10faf866-ef2a-49d8-925f-78c2423c9bc7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-09T12:00:00+00:00'
            elementCondition: null
            heading: 'Section Content'
            type: craft\fieldlayoutelements\Heading
            uid: 5acbde83-1b1f-4dfc-a507-c7b5517c8d91
            userCondition: null
          -
            dateAdded: '2026-09-09T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7f0dd947-99d8-4456-93f3-4ce4f6162a3f # Rich Text - Simple
            handle: text
            instructions: null
            label: Text
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c833db87-00ed-4066-a874-0ed552dc7942
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-09T12:00:00+00:00'
            elementCondition: null
            heading: 'Section Footer'
            type: craft\fieldlayoutelements\Heading
            uid: d86051e7-b1ca-4f66-ac55-5052935938a7
            userCondition: null
          -
            dateAdded: '2026-09-09T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 298fa7b6-abc0-4c80-a004-8fa35a30bf35 # Button Group
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c48e3ce-6a34-4aea-985d-3fff01cef8e1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 85b159ae-71c3-437a-ab7e-c1802652b053
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-09T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 502c0610-e74d-4359-8524-5652307ada64 # Padding
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a80d3f4-63f7-42b3-a861-811775b5965e
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 3f151e43-20d6-4003-ae4a-bb8fd0c01626
        userCondition: null
    thumbFieldKey: null
handle: eyebrowHeadingText
hasTitleField: false
icon: align-left
name: 'Eyebrow, Heading & Text'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
