allowLineBreaksInTitles: false
color: blue
description: null
fieldLayouts:
  e2b895eb-9633-4685-8b17-bcb962b4ad5c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-28T11:29:36+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bb417d14-872a-4288-9f03-8a735011cb7e # Eyebrow
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba8f87e5-4953-4893-a391-c6c1393f9d05
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T11:29:36+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d5189384-3a6a-441f-9f4b-cb171f279337 # Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9dff1b26-9c97-40ec-a050-b79668992661
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-28T11:29:36+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7f0dd947-99d8-4456-93f3-4ce4f6162a3f # Rich Text - Simple
            handle: text
            instructions: null
            label: Text
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c3a6312-688c-4bfd-97fb-1307d1013b6b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 08922261-cfaa-431c-a0f8-9e0daafc5855
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-08-28T11:29:36+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9c2880cd-7d0d-494f-aeeb-4c0b30575fb5 # Padding - Hero
            handle: padding
            instructions: null
            label: Padding
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5926cc89-9e18-405e-895c-223d8403eebc
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: abae0d7e-7a1f-481d-a058-9329482fed5b
        userCondition: null
    thumbFieldKey: null
handle: heroSimple
hasTitleField: false
icon: heading
name: 'Hero - Simple'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
