allowLineBreaksInTitles: false
color: purple
description: null
fieldLayouts:
  27803a41-d675-4bd9-8518-e52cec7f5b67:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-09T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: icon
            instructions: 'The Font Awesome icon name, e.g. bullseye-arrow. Always shown in the Sharp Duotone Light style.'
            label: Icon
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f5202b0-f328-4b9c-b172-e4247bc6c1e2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-09T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: heading
            instructions: null
            label: Heading
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9c9ccc9-3a8d-4b65-9adc-908e2ea1b0a4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-09T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7f0dd947-99d8-4456-93f3-4ce4f6162a3f # Rich Text - Simple
            handle: text
            instructions: null
            label: Text
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d916ceeb-4780-4a9d-bc8d-d19743d9fca9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0415f72c-a4e8-4ba9-8a1c-1835957ba0ed
        userCondition: null
    thumbFieldKey: null
handle: iconCard
hasTitleField: false
icon: star
name: 'Icon Card'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{heading}'
