allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  71338575-8014-4de7-9d3d-532dac75025e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-01T13:52:16+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5cbe08b7-b4bd-4a6b-be41-de9647b5eb19 # Images
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfaf5573-9c8a-4d44-a5ae-b7592b3790c4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 62fa4ddf-eba0-41b5-94b0-ef658a420ace
        userCondition: null
    thumbFieldKey: null
handle: images
hasTitleField: false
icon: images
name: Images
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
