allowLineBreaksInTitles: false
color: blue
description: null
fieldLayouts:
  a0f3ccce-c980-4a6d-ab4b-6f8c732e761a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-03T12:08:02+00:00'
            elementCondition: null
            heading: 'Section Header'
            type: craft\fieldlayoutelements\Heading
            uid: 32f4ade0-3757-495c-a637-5d7bdb22c11b
            userCondition: null
          -
            dateAdded: '2026-09-03T12:08:02+00:00'
            elementCondition: null
            heading: 'Section Content'
            type: craft\fieldlayoutelements\Heading
            uid: aba5ab0f-320f-40cb-a467-4dd5c9c32100
            userCondition: null
          -
            dateAdded: '2026-09-03T12:08:02+00:00'
            elementCondition: null
            heading: 'Section Footer'
            type: craft\fieldlayoutelements\Heading
            uid: 55585416-a628-4ca5-b58c-e1d1c9b6c56f
            userCondition: null
        name: Content
        uid: aa2f66c0-8e82-4632-918b-325d22aa9ba0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-03T12:08:02+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 502c0610-e74d-4359-8524-5652307ada64 # Padding
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 388f7680-573e-41fa-872b-26271972e808
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: dd54b809-94de-4f30-8ad8-8ce78babcf26
        userCondition: null
    thumbFieldKey: null
handle: template
hasTitleField: false
icon: cube
name: Template
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
