columnSuffix: null
handle: blocks
instructions: null
name: Blocks
searchable: false
settings:
  createButtonLabel: 'New Block'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 0935a4e9-bdf6-4843-a0bf-d8b3bcaa919b # Carousel - Case Study
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - c72c0ecf-e02d-4d76-893c-18b1b2d9f1b6 # Carousel - Service
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 8a84de3a-19bd-4528-a47b-1d207eda9858 # Heading
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 2c91993f-dfdf-4328-8eb3-a4a6adbe44cb # Heading Image Grid
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - ee7c6ba5-113d-47b8-aac7-4d8e6018f645 # Heading Reveal
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - f54fdb7f-5fd1-41e9-a4c3-63791f1316b8 # Marquee - Client
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - a644e662-8b0e-44bd-bbac-da76b709e24f # Statistics
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - d1bfe36b-4da4-4c86-a162-fa22d76b4ed8 # Template
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
