columnSuffix: null
handle: blocks
instructions: null
name: Blocks
searchable: false
settings:
  createButtonLabel: 'New Block'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - d8925826-0e82-41f9-91e8-bb798d884868 # Carousel - Blog
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 0935a4e9-bdf6-4843-a0bf-d8b3bcaa919b # Carousel - Case Study
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 757798ef-4636-48d7-92ab-a4f0de5f9340 # Carousel - Featured Team
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - c72c0ecf-e02d-4d76-893c-18b1b2d9f1b6 # Carousel - Service
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 823de6d3-c67e-4f53-b852-0983c35aab97 # Elements - FAQ
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - ed7d1592-7563-4406-aba9-cbdf547d198d # Elements - Testimonial
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 0acf1fd0-9723-4b0b-905b-b873b17bfdf7 # Eyebrow, Heading & Text
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 79e1a77d-effa-4dd3-bdb7-0887b8151560 # Featured Testimonial
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 8a84de3a-19bd-4528-a47b-1d207eda9858 # Heading
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 2c91993f-dfdf-4328-8eb3-a4a6adbe44cb # Heading Image Grid
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - ee7c6ba5-113d-47b8-aac7-4d8e6018f645 # Heading Reveal
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - eb6e087e-6699-4170-b63e-4ffb637101be # Icon Grid
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - f54fdb7f-5fd1-41e9-a4c3-63791f1316b8 # Marquee - Client
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - fa94fd7e-c6f7-4d8a-a3d3-71a00e095d43 # Marquee - Logos
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - a644e662-8b0e-44bd-bbac-da76b709e24f # Statistics
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 2173f8fc-5044-44ea-a7ca-a776fbdca208 # Stacking Cards
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 4155d79e-8997-463c-8e4f-8e9fea348e1e # Content Rows
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - d1bfe36b-4da4-4c86-a162-fa22d76b4ed8 # Template
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 7fbdabfa-25d4-4019-acca-997cce421316 # Timeline
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 9bc3b5b3-8512-4246-b1b8-d78eb6798dd5 # Video Content
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 95724d2a-e278-4525-aac3-1f88dcf163ee # Video
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - af21bfea-8fd9-454d-aebe-0a21a6be6d5b # Video - CTA
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
