columnSuffix: null
handle: dropdownTextColour
instructions: null
name: 'Dropdown - Text Colour'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - White
        -
          - value
          - white
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Black
        -
          - value
          - black
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
