columnSuffix: null
handle: dropdownLinks
instructions: null
name: 'Dropdown Links'
searchable: false
settings:
  createButtonLabel: 'New Dropdown'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 20537208-537a-47ea-81e3-2e1d4d5107ef # Links To & Image
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
