columnSuffix: null
handle: listItems
instructions: null
name: 'List Items'
searchable: false
settings:
  createButtonLabel: 'New List Item'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 0ab10d66-71d5-42dc-862d-83bb9341edb5 # List Item
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
