dateModified: 1789053892
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      page: Entries
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: 'section:dd193fca-6353-485f-a383-668951cbb602' # Blog
      page: Entries
      type: native
    -
      key: 'section:507a5f9c-bcbc-410d-a04f-48829ea6f806' # Case Study
      page: Entries
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:7b662bcd-ea91-4c91-86ce-c60348c664d1' # Page
      page: Entries
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: 'section:01db3114-eb35-4fde-a697-e47250abb979' # Playbook
      page: Entries
      type: native
    -
      key: 'section:6940873f-5b46-423d-9177-02a507f9772d' # Service
      page: Entries
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:15a9b54f-c692-49c5-9368-7a85274cd550' # Career
      page: Elements
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: 'section:fa2d89b4-fa6d-48d3-b36a-7169022cd64d' # Client
      page: Elements
      type: native
    -
      key: 'section:bcef1181-692a-4647-9320-f85c0285fbf9' # Testimonial
      page: Elements
      type: native
    -
      key: 'section:9b4079ae-fa59-4930-8132-039a9456c37c' # FAQ
      page: Elements
      type: native
    -
      key: 'section:cfeb9855-4c2c-423d-b40b-57d2dd12b46e' # Team
      page: Elements
      type: native
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: false
      key: singles
      page: Globals
      tableAttributes:
        - status
        - link
      type: native
elementSourcesPages:
  craft\elements\Entry:
    Elements:
      icon: elementor
    Entries:
      icon: file
    Globals:
      icon: earth-americas
email:
  fromEmail: $CRAFT_SYSTEM_EMAIL
  fromName: $CRAFT_SITE_NAME
  replyToEmail: null
  template: _emails/system.twig
  transportSettings:
    apiKey: $MAILGUN_API_KEY
    domain: $MAILGUN_DOMAIN
    endpoint: $MAILGUN_ENDPOINT
  transportType: craft\mailgun\MailgunAdapter
fs:
  craftCloud:
    hasUrls: true
    name: 'Craft Cloud'
    settings:
      baseUrl: null
      expires: '1 years'
      localFsPath: '@webroot/uploads'
      localFsUrl: /uploads
      subpath: null
    type: craft\cloud\fs\AssetsFs
  local:
    hasUrls: true
    name: Local
    settings:
      path: $FILESYSTEM_LOCAL_BASE_PATH
    type: craft\fs\Local
    url: $FILESYSTEM_LOCAL_BASE_URL
  servd:
    hasUrls: true
    name: Servd
    settings:
      cdnUrlPattern: ''
      customSubfolder: ''
      disableTransforms: false
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
      subfolder: /local/
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://cdn2.assets-servd.host/'
meta:
  __names__:
    0acf1fd0-9723-4b0b-905b-b873b17bfdf7: 'Eyebrow, Heading & Text' # Eyebrow, Heading & Text
    0b4c11ad-51c9-43b6-a7cd-47a988cc8821: 'Contact Column' # Contact Column
    0b199c11-0b79-4e4b-b931-f9c85e23a667: Button # Button
    0c7ab01e-612c-4ca5-ae2c-697d5c4dcfcf: Milestone # Milestone
    1d852893-eb82-4886-afbd-030682a843f8: 'Entries - Testimonial' # Entries - Testimonial
    01db3114-eb35-4fde-a697-e47250abb979: Playbook # Playbook
    1e8bf0d4-be2b-4c71-8c62-e6cbe9bc401d: Email # Email
    1e92fbd1-878b-44df-b3fc-d00b32474e6d: 'Entry - FAQ' # Entry - FAQ
    1ef24d74-b2e4-412d-b234-8766de50c3b6: 'Hero - Simple' # Hero - Simple
    1fca19db-a5b4-4b81-addd-5d2fa40bb83d: 'Button - No Label' # Button - No Label
    2a8d639a-2f4a-4d25-9385-ddac09ecc1ce: 'Footer Columns' # Footer Columns
    2a539981-3459-4d5f-8713-9d29353feafe: 'Longform Video' # Longform Video
    2b6ef296-14ae-4934-80de-4094433f69aa: Blog # Blog
    2c91993f-dfdf-4328-8eb3-a4a6adbe44cb: 'Heading Image Grid' # Heading Image Grid
    2cc195a7-75c4-4cb5-baba-42a69362e622: 'Dropdown - Video Display Type' # Dropdown - Video Display Type
    2fa69ca1-0da9-4b6b-910a-16d9b40d3cad: File # File
    2fdcc5f0-cba6-486c-a080-20852b3bf4bd: 'Entry - Client' # Entry - Client
    4cca2129-e042-4a21-9fa8-29d23e75875d: 'Categories - Case Study' # Categories - Case Study
    5cbe08b7-b4bd-4a6b-be41-de9647b5eb19: Images # Images
    5e0a0379-473d-48fa-b3f0-4230ddc449a6: 'Lightswitch - Off' # Lightswitch - Off
    5e4babbb-3468-4302-9765-12fa4e367fe4: 'Longform Image Columns' # Longform Image Columns
    5edf3cb2-e081-444a-a9c1-bdab388c26f3: 'Dropdown - Aspect Ratio' # Dropdown - Aspect Ratio
    6b543e86-8407-40c1-a8c3-f313ed625200: 'Entry - Form Success' # Entry - Form Success
    6b2462c2-66b9-45fe-9504-0bce4d4cd1df: Blocks # Blocks
    6c529af8-e2a5-4453-b9fb-1ba91313d2ea: 'Dropdown - Icon Type' # Dropdown - Icon Type
    6c903676-c7fc-4096-874c-68b19495c33a: 'Entry - Service' # Entry - Service
    6d792fe4-471d-48ed-bc45-5fe112ba7e46: Image # Image
    6f7c5bc5-e419-4241-8b4e-4598a736cafd: 'Entry - Team Listing' # Entry - Team Listing
    7b662bcd-ea91-4c91-86ce-c60348c664d1: Page # Page
    7bf65ac5-9169-4bf8-8825-65fadd566946: New # New
    7da91603-5ded-43ca-b8c9-692b445e049e: 'Rich Text - Longform' # Rich Text - Longform
    7f0dd947-99d8-4456-93f3-4ce4f6162a3f: 'Rich Text - Simple' # Rich Text - Simple
    7fbdabfa-25d4-4019-acca-997cce421316: Timeline # Timeline
    8a84de3a-19bd-4528-a47b-1d207eda9858: Heading # Heading
    8b233bdd-f329-4553-af8e-2f8f4156f8cf: 'Menu Column' # Menu Column
    08c386f4-5a41-4c9f-8282-f6785af06bfc: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    8dec68ee-43b1-4ee4-adaf-09353f5bfab8: 'Entry - Testimonial' # Entry - Testimonial
    9b4079ae-fa59-4930-8132-039a9456c37c: FAQ # FAQ
    9bc3b5b3-8512-4246-b1b8-d78eb6798dd5: 'Video Content' # Video Content
    9c2880cd-7d0d-494f-aeeb-4c0b30575fb5: 'Padding - Hero' # Padding - Hero
    9da49a9d-23bf-4f1f-b736-5d8465f335ab: 'Entry - Case Study' # Entry - Case Study
    9db15396-a721-4413-a2c2-72e509359139: 'Entry - Contact' # Entry - Contact
    9de44452-8794-4e21-b47e-f1adf6c262eb: 'Hero Template' # Hero Template
    9f7a3bdc-1be7-4939-9cb1-6472c41ba7c2: 'Marquee - Team' # Marquee - Team
    15a9b54f-c692-49c5-9368-7a85274cd550: Career # Career
    15e52e57-510c-4224-9b47-16c703f5270c: Images # Images
    17c07940-d39d-4d93-801d-5a752b9c40ec: 'Entry - Career' # Entry - Career
    17e2f019-d6ee-4f54-83a2-a32091caa96d: 'Button Group (Unlimited)' # Button Group (Unlimited)
    19d6d897-1cde-4d59-914a-2bf8a23e7916: 'Public Schema' # Public Schema
    34e8bb72-5cc9-4fa5-a269-e556b5cd8fd2: 'Icon Card' # Icon Card
    42eea3c2-2f84-43d8-a495-647d4994a8d5: 'Text - Multiline' # Text - Multiline
    43da3acd-b36b-47e5-b95c-d22e2c6454de: 'Video - Only' # Video - Only
    45cc8008-35a7-450e-afb4-5756ca2222d9: 'Dropdown - Background Colour' # Dropdown - Background Colour
    68e3deec-735b-4dca-b597-68e68e8777f0: Accordions # Accordions
    72cd3ad5-6f02-4c3b-b431-be5e96bda8e9: 'Entry - Playbook' # Entry - Playbook
    74eb57f4-3401-46b7-a35b-e2a75fee9c63: Button # Button
    75b9e023-7720-4105-a4af-520f42961eb7: Service # Service
    75cd72a0-08d7-4e62-987d-3380ee5a0722: 'Entry - FAQ Listing' # Entry - FAQ Listing
    77b77dda-5b66-418a-8f88-158a1830c6cd: 'Entry - Blog Listing' # Entry - Blog Listing
    79e1a77d-effa-4dd3-bdb7-0887b8151560: 'Featured Testimonial' # Featured Testimonial
    87b41f87-eee1-44ce-8484-cae9e5b58b3b: 'Entries - Client' # Entries - Client
    93bb0c13-89fe-4d68-9853-576b7d1238a6: 'Entry Site' # Entry Site
    94a26b89-4e28-433a-91e9-894a0248710f: 'Categories - Service' # Categories - Service
    101f8024-59d6-48df-9744-ccf3da6ef824: 'Dropdown - Star Rating' # Dropdown - Star Rating
    250a614d-a573-422d-aeed-1716dd6d4d5e: 'Scrolling Cards' # Scrolling Cards
    298fa7b6-abc0-4c80-a004-8fa35a30bf35: 'Button Group' # Button Group
    419fd065-b523-4ca1-b185-1b82546c312b: 'Scrolling Cards' # Scrolling Cards
    443a1739-83a4-481f-bcf4-71cd0d14bb00: 'Entry - Blog' # Entry - Blog
    453f9294-407d-405a-b73b-d5b63aec2eaa: SEO # SEO
    502c0610-e74d-4359-8524-5652307ada64: Padding # Padding
    507a5f9c-bcbc-410d-a04f-48829ea6f806: 'Case Study' # Case Study
    637e921f-8b1c-495b-af4e-4ad4d4402c04: 'Content Row' # Content Row
    823de6d3-c67e-4f53-b852-0983c35aab97: 'Elements - FAQ' # Elements - FAQ
    924b795e-4490-4ca2-8b11-42c1f2ff31f1: 'Content Rows' # Content Rows
    0935a4e9-bdf6-4843-a0bf-d8b3bcaa919b: 'Carousel - Case Study' # Carousel - Case Study
    01475e1b-7d73-4ffa-868e-7dbcb87d00a9: 'Heading - Inline Images' # Heading - Inline Images
    2173f8fc-5044-44ea-a7ca-a776fbdca208: 'Stacking Cards' # Stacking Cards
    2451f9f6-405a-429f-9abb-a2acde87159a: 'Entries - Services' # Entries - Services
    2634aee9-724f-4029-a0fb-d1e3b7d3fc38: 'Main Menu' # Main Menu
    3731f571-53b0-4cf2-a89a-dbc6a4adc351: 'Longform Image' # Longform Image
    4155d79e-8997-463c-8e4f-8e9fea348e1e: 'Content Rows' # Content Rows
    4580bc09-b5c8-40a2-bff5-95f715403f50: Video # Video
    5200f937-8d03-490c-bebc-4fb1e0c06c4a: 'Menu Item' # Menu Item
    05236f38-ec1c-4446-93a8-43c0b72e45ac: 'Banner - CTA' # Banner - CTA
    6708a79d-c929-45c4-82f1-b440db7d759d: 'Dropdown - Video Type' # Dropdown - Video Type
    7754a8a1-7a07-4f58-903a-10ae9e993341: 'Categories - Blog' # Categories - Blog
    8921f4cc-6d1a-4c1f-bf13-bcdf8b992806: Links # Links
    13116ff7-bb9e-4f5b-989d-48a287e4b53c: 'Text - Code' # Text - Code
    41118d3a-a4e2-4b8e-8d11-b0a93f26deeb: 'Lightswitch - On' # Lightswitch - On
    42537cb1-23aa-402e-a410-ffed07a3685b: Statistic # Statistic
    95724d2a-e278-4525-aac3-1f88dcf163ee: Video # Video
    401508ab-1703-4248-86c6-2adf4ccc7ea9: 'Links To' # Links To
    716706e7-230b-4ae4-ad62-ba31b432c578: Site # Site
    757798ef-4636-48d7-92ab-a4f0de5f9340: 'Carousel - Featured Team' # Carousel - Featured Team
    868256be-34c2-4060-9427-94a7d25d97a2: 'Entry - Service Listing' # Entry - Service Listing
    6940873f-5b46-423d-9177-02a507f9772d: Service # Service
    8053567b-728a-491a-9206-0c9a6c6b1b12: 'Footer CTA' # Footer CTA
    9096937b-3ea8-4e92-a2bc-2a4b495b2b9c: 'Dropdown - Content Order' # Dropdown - Content Order
    13285537-5457-4f1f-ad8c-66fd187f8f09: 'Rich Text - Full' # Rich Text - Full
    50116844-aee8-4cad-ae6f-cb59132a4d62: 'Entries - Team' # Entries - Team
    76599613-117c-4ce5-b344-172d2aff2194: 'Entries - Case Study' # Entries - Case Study
    a5b03fa9-9f1f-47a5-ba3e-9a3c61f706d5: 'Case Study' # Case Study
    a644e662-8b0e-44bd-bbac-da76b709e24f: Statistics # Statistics
    ab214509-2da1-4b0b-b7a3-33dac1c86ce9: Hero # Hero
    acbe31d2-326d-4dca-b857-3ccf50f3efdc: 'Hero - Home' # Hero - Home
    af21bfea-8fd9-454d-aebe-0a21a6be6d5b: 'Video - CTA' # Video - CTA
    b6d2560f-cae8-458b-9d36-e66efde2f247: 'Entries - Blog' # Entries - Blog
    b9ac68e1-d9f1-4007-843f-fde1e9f4921b: Files # Files
    bb417d14-872a-4288-9f03-8a735011cb7e: Eyebrow # Eyebrow
    bcef1181-692a-4647-9320-f85c0285fbf9: Testimonial # Testimonial
    bd5792c0-8d1f-4b0d-8340-8ae589fec77d: 'Longform - Quote' # Longform - Quote
    bdf6317d-0df7-449f-a937-a1a274ffb106: 'Entry - Blocks' # Entry - Blocks
    c019bbe6-8d43-4e78-9158-eb2c865818e9: 'Entry - Playbook Listing' # Entry - Playbook Listing
    c0203d6f-4eda-4753-879f-9c36db1c1a98: Date # Date
    c08276b4-951f-4222-9e12-73622b78b6e0: 'Avatar Group' # Avatar Group
    c3b9838a-6581-409e-9730-3fecbd013c89: Phone # Phone
    c72c0ecf-e02d-4d76-893c-18b1b2d9f1b6: 'Carousel - Service' # Carousel - Service
    c354f48d-60f1-4040-825e-be40e03acd40: 'Entries - FAQ' # Entries - FAQ
    c803bdbf-5bdd-43e8-94e2-c7cde210fe37: 'Links To' # Links To
    cb6226c7-5901-41ed-ba28-a78b9504a3df: Images # Images
    cb336128-ebff-454c-84e0-9248097d4604: 'Images (Max 3)' # Images (Max 3)
    ce59fcb1-fb86-46a3-81a4-f7d745761454: 'Entry - Case Study Listing' # Entry - Case Study Listing
    cf9f3773-3ba1-41d3-b95f-5467d0b9227a: 'Dropdown - Alignment' # Dropdown - Alignment
    cfeb9855-4c2c-423d-b40b-57d2dd12b46e: Team # Team
    d1bfe36b-4da4-4c86-a162-fa22d76b4ed8: Template # Template
    d2a9f8dd-ebb9-4d78-a006-11ad40465058: Timeline # Timeline
    d6ef3fab-743e-41b5-bd93-a0a4c3cf42dd: 'Accordion Item' # Accordion Item
    d35d937a-07ca-4c88-bd62-1f65c807aa15: Statistics # Statistics
    d99bf7af-1eb1-4b77-814e-624eeec1a0e3: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    d5189384-3a6a-441f-9f4b-cb171f279337: Heading # Heading
    d8925826-0e82-41f9-91e8-bb798d884868: 'Carousel - Blog' # Carousel - Blog
    da9f3d8e-5ba9-4eb9-a423-6ea09ddaed21: Form # Form
    db56c11b-226d-42e6-9b9b-b449f0ac99df: 'Entry - Testimonial' # Entry - Testimonial
    dd193fca-6353-485f-a383-668951cbb602: Blog # Blog
    e09df1c8-18b1-4598-ad75-812ac48e1b9c: 'Dropdown - Media Type' # Dropdown - Media Type
    e3078af5-a566-4561-af12-e529edd7980f: 'Entry - Team' # Entry - Team
    e746909c-3d0f-4818-9497-14651dc6ee16: 'Entry - Text' # Entry - Text
    ea300912-bfa1-429b-9212-ba39329d1960: 'Stacking Card' # Stacking Card
    eb5e339e-d658-4112-9895-62287412dd93: 'Image Columns (Max 2)' # Image Columns (Max 2)
    eb6e087e-6699-4170-b63e-4ffb637101be: 'Icon Grid' # Icon Grid
    ecf96135-0c9d-4684-888c-9e3bd7def9bc: 'Longform Button Group' # Longform Button Group
    ed7d1592-7563-4406-aba9-cbdf547d198d: 'Elements - Testimonial' # Elements - Testimonial
    ee7c6ba5-113d-47b8-aac7-4d8e6018f645: 'Heading Reveal' # Heading Reveal
    eebfd246-f9aa-4d59-99e5-d4aaba54acba: 'Entry - Brand Guidelines' # Entry - Brand Guidelines
    f3e544b8-88bf-4761-8df2-d767fa1502b7: Text # Text
    f7b5b560-85eb-4827-a39b-b24c863ae5c3: 'Links To - No Label' # Links To - No Label
    f7b9ffb6-c3c5-4bef-98aa-844c0fe6f842: 'Scrolling Card' # Scrolling Card
    f8dddc0d-c81b-4fd7-97b0-25873d6023f6: 'Hero - Full Screen' # Hero - Full Screen
    f18e57cc-fd7c-4892-a604-aa68a1598318: 'Stacking Cards' # Stacking Cards
    f54fdb7f-5fd1-41e9-a4c3-63791f1316b8: 'Marquee - Client' # Marquee - Client
    fa2d89b4-fa6d-48d3-b36a-7169022cd64d: Client # Client
    fa94fd7e-c6f7-4d8a-a3d3-71a00e095d43: 'Marquee - Logos' # Marquee - Logos
    fb0420bb-0fbf-46d2-afd2-f7992c60c886: 'Contact Form' # Contact Form
    fc1aa366-1ece-49df-90bc-917b65b70e7d: 'Icon Grid' # Icon Grid
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: W86FSHSR2PLIQPTHPVF1NWQF
    schemaVersion: 5.12.0
    settings:
      maxUriLength: 2048
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 5.6.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: 31GHAV4SZ3J6SVPPKESB9XL2
    schemaVersion: 3.4.12
  imager-x:
    edition: lite
    enabled: true
    licenseKey: X8XTY98DNH63HUL8XCX3SAHC
    schemaVersion: 4.0.0
  imager-x-craft-cloud-transformer:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  llm-ready:
    edition: standard
    enabled: true
    schemaVersion: 1.3.0
    settings:
      enableUserAgentDetection: true
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 3TKVKXGN8QLRHD9D8SKUG90G
    schemaVersion: 3.0.13
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      adjustFeedmeLogs: ''
      assetsEnvironment: $SERVD_ASSET_ENVIRONMENT
      assetsEnvironmentOverwrite: ''
      cacheClearMode: full
      clearCachesOnSave: never
      disableDynamic: ''
      disableTransforms: ''
      fsMapsEnabled: ''
      imageAutoConversion: webp
      injectCors: '1'
      projectSlug: $SERVD_PROJECT_SLUG
      securityKey: $SERVD_SECURITY_KEY
      suppressWarnings: '1'
      useLocalVolumes: false
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: $CRAFT_SITE_NAME
  schemaVersion: 5.10.0.0
  timeZone: Europe/London
