defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9da49a9d-23bf-4f1f-b736-5d8465f335ab # Entry - Case Study
handle: caseStudy
maxAuthors: 1
minAuthors: 1
name: 'Case Study'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _entryTypes/base.twig
    uriFormat: 'case-study/{slug}'
structure:
  maxLevels: null
  uid: 9adf2bb6-1391-4c13-bf46-864ac5d734d4
type: structure
