defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d90e2274-f99e-4cdd-946f-9505a2caf8c9 # Entry Global Blocks
handle: globalBlocks
maxAuthors: 1
minAuthors: 1
name: 'Global Blocks'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
