defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e3078af5-a566-4561-af12-e529edd7980f # Entry - Team
handle: team
maxAuthors: 1
minAuthors: 1
name: Team
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 2480ad58-77cc-4783-8afc-97c142fbd894
type: structure
