defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 8dec68ee-43b1-4ee4-adaf-09353f5bfab8 # Entry - Testimonial
handle: testimonial
maxAuthors: 1
minAuthors: 1
name: Testimonial
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
